# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-DNS-Async
version:      1.06
version_from: lib/Net/DNS/Async.pm
installdirs:  site
requires:
    IO::Select:                    0
    Net::DNS:                      0
    Storable:                      0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
